config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :groups do
    resources :comments
    member do
      post 'upvote'
    end
    collection do
      get :search
    end
  end

  resources :aboutme
  resources :categories

  root "groups#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  is_impressionable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :groups
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  validates :content, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence: true  # 为何要写在model中：因为model掌管数据库，你做的事情，如果model检查不通过，它就不把数据存到数据库里。你能咋的？
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :votes, dependent: :destroy 
  belongs_to :category

end

app/models/kindeditor/asset.rb
class Kindeditor::Asset < ActiveRecord::Base
  self.table_name = 'kindeditor_assets'
  mount_uploader :asset, Kindeditor::AssetUploader
  validates_presence_of :asset
  before_save :update_asset_attributes
  
  private
  def update_asset_attributes
    if asset.present? && asset_changed?
      self.file_size = asset.file.size
      self.file_type = asset.file.content_type
    end
  end
end

app/models/kindeditor/file.rb
class Kindeditor::File < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::FileUploader
end

app/models/kindeditor/flash.rb
class Kindeditor::Flash < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::FlashUploader
end

app/models/kindeditor/image.rb
class Kindeditor::Image < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :group
end

app/controllers/aboutme_controller.rb
class AboutmeController < ApplicationController

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, warning: "你已删除这个分类"
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def create
      @group = Group.find(params[:group_id])
      @comment = @group.comments.new(comment_params)

      if @comment.save
        redirect_to group_path(@group), notice: "已评论"
      else
        redirect_to group_path(@group), notice: "内容不能为空"
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  impressionist actions: [:show]
  before_action :validate_search_key, only: [:search]

  def index
      if params[:category].blank?
      @groups = Group.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)     # controller 找到数据库里的所有的group数据，把它赋值给变量@groups。@groups这个变量，提供给groups/index.html.erb使用。
    else
      @category_id = Category.find_by(name: params[:category]).id
      @groups = Group.where(category_id: @category_id).order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    end
  end

  def show
    @group = Group.find(params[:id])   # ID就是http://localhost:3000/groups/1里的1.在数据库表里找到ID是1的group信息，把它赋值给实体变量@group，显示出来
    @comments = @group.comments
  end

  def new
    @group = Group.new   #在数据库里新建一个讨论组，并把它赋值给@group
    @categories = Category.all.map { |c| [c.name, c.id]}
  end

  def create
    @group = Group.new(group_params)    #从数据库里找到新建的group，（group params 只允许应该修改的栏位修改），把它的值传给实体变量@group
    @group.category_id = params[:category_id]
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id]}
  end

  def update
    @group = Group.find(params[:id])  # 在数据库表中根据group的ID找到相应的group，把值传给实体变量@group
    @group.category_id = params[:category_id]
    if @group.update(group_params)       # 实体变量@group对group params 进行更新
      redirect_to groups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])   # 在数据库表中根据group的ID找到相应的group，把值传给实体变量@group
    @group.destroy                     # 实体变量@group里的数据，毁掉
    flash[:alert] = "Group deleted"
    redirect_to groups_path
  end

  def upvote
    @group = Group.find(params[:id]) # 在Group的数据库里，根据group的ID找到这个group，把它交给@group
    @group.votes.create  #给@group创建一个点赞
    redirect_to(group_path)  # 创建完毕后，返回group的show页面。
  end

  def search
     if @query_string.present?
        search_result = Group.ransack(@search_criteria).result(:distinct => true)
        @groups = search_result.paginate(:page => params[:page], :per_page => 5 )
      end
  end

  private

  def group_params
    params.require(:group).permit(:title, :description, :image, :category_id)
  end

  protected

     def validate_search_key
       @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
       @search_criteria = search_criteria(@query_string)
     end

     def search_criteria(query_string)
       { title_or_description_cont: query_string }
     end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



end

app/helpers/aboutme_helper.rb
module AboutmeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end

end

app/helpers/groups_helper.rb
module GroupsHelper

  def render_highlight_content(group,query_string)
      excerpt_cont = excerpt(group.title, query_string, radius: 500)
      highlight(excerpt_cont, query_string)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/edit.html.erb
<h1> edit分类</h1>

<%= simple_form_for @category do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h2> 分类列表 </h2>

<div class="pull-right">
  <%= link_to '新的分类', new_category_path, class: 'btn btn-primary'%>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>

      <th>名称</th>
      <th colspan="2">设置</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= category.name%></td>
      <td><%= link_to '编辑',edit_category_path(category)%></td>
      <td><%= link_to '删除',category_path(category),method: :delete, data: {confirm: '你确定要删除吗'}%></td>
    </tr>
    <% end %>

  </tbody>
  
</table>

app/views/categories/new.html.erb
<h1> 新增分类</h1>

<%= simple_form_for @category do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for [@group,@group.comments.build] do |f| %>
    <div class="form-group">
      <%= f.input :content, label: "发表评论", input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "发表", disable_with: "Submiting...", class: "btn btn-xs btn-default"%>
    </div>
  <% end %>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
<div class="group">
   <%= select_tag(:category_id, options_for_select(@categories), :prompt => "类别")%>
 </div>
  <div class="form-group">

    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.kindeditor :description %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑讨论版</h2>

    <hr>
  

    <%= render "form" %>

</div>

app/views/groups/index.html.erb
<div>
  <% if current_user %>
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <% end %>
  <table class="table home-index">
    <thead class="index-head">
      <tr>
        <td style="text-align:center">文章列表</td>
        <td>发布时间</td>
        <td>阅读次数</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
      <!-- 从controller index里 传过来的变量 @groups，里面有很多的数据。 把每个数据遍历一遍，形成一个表格   -->
        <tr>
          <td width="60%" style="border: 1px dotted white; text-align:center"> <%= link_to(group.title, group_path(group)) %> </td>
          <td width="25%" style="border: 1px dotted white"><%= group.created_at.localtime.strftime("%Y/%m/%d") %></td>
          <% if current_user%>
          <td>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
                          <!-- method：：delete 是一个需要按钮才触发的动作。 data 是触发信息的方法。  -->
          </td>
          <% end %>
          <td width="15%"  style="border: 1px dotted white">  <%= "#{group.impressionist_count} 次" %></td>
        </tr>
      <% end %>

    </tbody>

  </table>
  <div class="text-center paginate-dzl">
    <div style="border-bottom:1px dashed #d6d6d6;margin:5px"></div>

    <%= will_paginate @groups, :previous_label => '上一页', :next_label => '下一页', :class => "flickr_pagination" %>
  </div>

</div>

app/views/groups/new.html.erb
<div>
  <h2>添加文章</h2>

  <hr>
  
  <%= render "form" %>

</div>

app/views/groups/search.html.erb
<div class="home-index">
  <div class="container">
    <!--=== 搜索结果，没有符合条件的数据 ===-->
    <% if @query_string.blank? %>
      <h2 class="search-info-title">搜索信息不能为空，请输入关键字搜索</h2>
    <% elsif @groups.blank?%>
      <br>
        <h2 class="search-info-title">亲，没有搜索到文章哦，要不换个关键词试试？</h2>
    <% else %>
    <!--=== 搜索结果，有符合条件的数据 ===-->
    <!--=== 搜索內容 ===-->
      <div class='row'>
       <% @groups.each do |group| %>
         <div class='col-xs-12 col-sm-4 col-md-3 product-content'>
           <div class="product-info">
            <p><%= link_to(render_highlight_content(group,@query_string), group_path(group)) %></p>
           </div>
         </div>
       </div>
       <div class="page-box">
         <%= will_paginate @groups, renderer: BootstrapPagination::Rails, :previous_label => t('previous-label'), :next_label => t('next-label') %>
       </div>
       <% end %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="col-md-12 home-index content-blog">
  <% if current_user %>
  <div class="group">
     <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%> <!--编辑实例变量@group的路径 -->
  </div>
  <% end %>
  <!-- @group的含义：在controller的show中，我们从数据库中根据group的ID找到了group的所有信息，把它传给了实力变量@group。 -->

  <h3 style="text-align:center"><%= @group.title %></h3>   <!-- 引用实例变量@group的title栏位 -->
  <div style="text-align:right">
    发布时间：<%= @group.updated_at.localtime.strftime("%Y/%m/%d") %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    阅读次数：<%= "#{@group.impressionist_count} 次" %>
  </div>
  <div style="border-bottom:1px dashed #d6d6d6;margin:5px"></div>
  <br><br>
  <p><%= raw @group.description %></p>
    <br><br>
    <div class="upvote">
        <%= link_to upvote_group_path(@group), method: :post do %>
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" style="color:#ff5722;"></span>
        <%= @group.votes.count %>次
       <% end %>
    </div>

</div>
<br>

<div class="col-md-12 space-margin"></div>
<div class="col-md-12 home-index content-blog">
  <table class="table">
      <thead>
        <tr>
          <th>评论内容</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td width=85%><%= comment.content %></td>
            <td width=15%><%= comment.created_at.localtime.strftime("%Y/%m/%d")  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-12 space-margin"></div>
  <div class="col-md-12 home-index content-blog">

    <%= render "comments/form" %>
  </div>
</div>