config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :groups do
    resources :comments
    member do
      post 'upvote'
    end
    collection do
      get :search
    end
  end

  resources :aboutme
  resources :categories

  root "groups#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  is_impressionable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :groups
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  validates :content, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence: true  # 为何要写在model中：因为model掌管数据库，你做的事情，如果model检查不通过，它就不把数据存到数据库里。你能咋的？
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :votes, dependent: :destroy 
  belongs_to :category

end

app/models/kindeditor/file.rb
class Kindeditor::File < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::FileUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :group
end

app/controllers/aboutme_controller.rb
class AboutmeController < ApplicationController

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, warning: "你已删除这个分类"
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def create
      @group = Group.find(params[:group_id])
      @comment = @group.comments.new(comment_params)

      if @comment.save
        redirect_to group_path(@group), notice: "已评论"
      else
        redirect_to group_path(@group), notice: "内容不能为空"
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  impressionist actions: [:show]
  before_action :validate_search_key, only: [:search]

  def index
      if params[:category].blank?
      @groups = Group.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)     # controller 找到数据库里的所有的group数据，把它赋值给变量@groups。@groups这个变量，提供给groups/index.html.erb使用。
    else
      @category_id = Category.find_by(name: params[:category]).id
      @groups = Group.where(category_id: @category_id).order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    end
  end

  def show
    @group = Group.find(params[:id])   # ID就是http://localhost:3000/groups/1里的1.在数据库表里找到ID是1的group信息，把它赋值给实体变量@group，显示出来
    @comments = @group.comments
  end

  def new
    @group = Group.new   #在数据库里新建一个讨论组，并把它赋值给@group
    @categories = Category.all.map { |c| [c.name, c.id]}
  end

  def create
    @group = Group.new(group_params)    #从数据库里找到新建的group，（group params 只允许应该修改的栏位修改），把它的值传给实体变量@group
    @group.category_id = params[:category_id]
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id]}
  end

  def update
    @group = Group.find(params[:id])  # 在数据库表中根据group的ID找到相应的group，把值传给实体变量@group
    @group.category_id = params[:category_id]
    if @group.update(group_params)       # 实体变量@group对group params 进行更新
      redirect_to groups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])   # 在数据库表中根据group的ID找到相应的group，把值传给实体变量@group
    @group.destroy                     # 实体变量@group里的数据，毁掉
    flash[:alert] = "Group deleted"
    redirect_to groups_path
  end

  def upvote
    @group = Group.find(params[:id]) # 在Group的数据库里，根据group的ID找到这个group，把它交给@group
    @group.votes.create  #给@group创建一个点赞
    redirect_to(group_path)  # 创建完毕后，返回group的show页面。
  end

  def search
     if @query_string.present?
        search_result = Group.ransack(@search_criteria).result(:distinct => true)
        @groups = search_result.paginate(:page => params[:page], :per_page => 5 )
      end
  end

  private

  def group_params
    params.require(:group).permit(:title, :description, :image, :category_id)
  end

  protected

     def validate_search_key
       @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
       @search_criteria = search_criteria(@query_string)
     end

     def search_criteria(query_string)
       { title_or_description_cont: query_string }
     end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



end

app/helpers/aboutme_helper.rb
module AboutmeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end

end

app/helpers/groups_helper.rb
module GroupsHelper

  def render_highlight_content(group,query_string)
      excerpt_cont = excerpt(group.title, query_string, radius: 500)
      highlight(excerpt_cont, query_string)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
   <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
     <button class="close" data-dismiss="alert">×</button>
     <%= value %>
   </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="id-footer" >
    <p class="text-center dzl-footer">俄语互联网资源精选  Copyright ©2016-2017   All Rights Reserved   吉ICP备16005439号-1
        <br>Design by 俄语人老杜工作室
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">俄语互联网资源精选</a>
            <div class="info-web">搜集<span style="font-style:oblique">&nbsp;&nbsp;好玩、有趣、有用&nbsp;&nbsp;</span>的互联网俄语资料</div>
        </div>


        <!-- 搜索框 -->

        <div class="nav navbar-nav search-navbar">
          <%= form_tag search_groups_path , :method => :get do %>
           <div class="input-group" id="search-id" >
              <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="搜索文章">
                <div class="input-group-btn">
                   <button class="btn  btn-default" type="submit">
                      <i class="glyphicon glyphicon-search"></i>
                   </button>
                </div>
            </div>
           <% end %>
        </div>

        <!-- 搜索框 完毕-->

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                  <!-- <li><%= link_to("注册", new_user_registration_path) %> </li> -->
                  <li><%= link_to("登录", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
                </li>
            </ul>
        </div>
    </div>

</nav>
<div >
  <% if current_user %>
      <%= link_to("Categories", categories_path)%>
  <% end %>
  <div class="index-head-1">
    <li class="category-index"><%= link_to("主页", groups_path) %>|</li>
    <% Category.all.each do |category| %>
      <li class="category-index" >
       <%= link_to(category.name, groups_path(category: category.name)) %> |
     </li>
    <% end %>
    <li class="category-index"><%= link_to("关于我", aboutme_index_path) %></li>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eyulaodu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="
    padding-bottom: 50px;">
      <%= render "common/navbar" %>
      <div class="main">
        <%= render "common/flashes" %>
        <%= yield %>
      </div>
  </div>
    <%= render "common/footer" %>
  </body>
</html>